#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["ApiGateway.Core/ApiGateway.Core.csproj", "ApiGateway.Core/"]
RUN dotnet restore "ApiGateway.Core/ApiGateway.Core.csproj"

COPY . .
WORKDIR "/src/ApiGateway.Core"
RUN dotnet build "ApiGateway.Core.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ApiGateway.Core.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ApiGateway.Core.dll", "--environment=Production"]